# -*- coding: UTF-8 -*-
# inspired by http://stackoverflow.com/a/3772008

from selenium import webdriver
import unittest

class TitleTest(unittest.TestCase):
    def __init__(self, url_path, title):
        super(TitleTest, self).__init__()
        self.url_path = url_path
        self.title = title

    def setUp(self):
        self.browser = webdriver.Firefox()
        self.browser.implicitly_wait(3)
        self.base_url = 'http://127.0.0.1:8000'

    def tearDown(self):
        self.browser.quit()

    def shortDescription(self):
        return 'page {} should contain {} in title'.format(
            self.url_path,
            self.title,
        )

    def runTest(self):
        self.browser.get(self.base_url + self.url_path)

        self.assertIn(self.title, self.browser.title)


def suite():
    known_values = (
        ('/admin/', 'Django site admin'),
        ('/admin/articles/article/', 'Django site admin'),
        ('/admin/articles/article/add/', 'Django site admin'),
        ('/admin/articles/articlecontentprovider/', 'Django site admin'),
        ('/admin/articles/articlecontentprovider/add/', 'Django site admin'),
        ('/admin/articles/articletype/', 'Django site admin'),
        ('/admin/articles/articletype/add/', 'Django site admin'),
        ('/admin/auth/group/', 'Django site admin'),
        ('/admin/auth/group/add/', 'Django site admin'),
        ('/admin/auth/user/', 'Django site admin'),
        ('/admin/auth/user/add/', 'Django site admin'),
        ('/admin/auth/user/send-email/', 'Django site admin'),
        ('/admin/blocks/infoblock/', 'Django site admin'),
        ('/admin/blocks/infoblock/add/', 'Django site admin'),
        ('/admin/blog/blog/', 'Django site admin'),
        ('/admin/blog/blog/add/', 'Django site admin'),
        ('/admin/blog/post/', 'Django site admin'),
        ('/admin/blog/post/add/', 'Django site admin'),
        ('/admin/bookmarks/bookmark/', 'Django site admin'),
        ('/admin/bookmarks/bookmark/add/', 'Django site admin'),
        ('/admin/comments/comment/', 'Django site admin'),
        ('/admin/comments/comment/add/', 'Django site admin'),
        ('/admin/comments/moderatordeletion/', 'Django site admin'),
        ('/admin/comments/moderatordeletion/add/', 'Django site admin'),
        ('/admin/comments/moderatordeletionreason/', 'Django site admin'),
        ('/admin/comments/moderatordeletionreason/add/', 'Django site admin'),
        ('/admin/configuration/sitesettings/', 'Django site admin'),
        ('/admin/configuration/sitesettings/add/', 'Django site admin'),
        ('/admin/contact_form/contactformcategory/', 'Django site admin'),
        ('/admin/contact_form/contactformcategory/add/', 'Django site admin'),
        ('/admin/djcelery/crontabschedule/', 'Django site admin'),
        ('/admin/djcelery/crontabschedule/add/', 'Django site admin'),
        ('/admin/djcelery/intervalschedule/', 'Django site admin'),
        ('/admin/djcelery/intervalschedule/add/', 'Django site admin'),
        ('/admin/djcelery/periodictask/', 'Django site admin'),
        ('/admin/djcelery/periodictask/add/', 'Django site admin'),
        ('/admin/djcelery/taskstate/', 'Django site admin'),
        ('/admin/djcelery/taskstate/add/', 'Django site admin'),
        ('/admin/djcelery/workerstate/', 'Django site admin'),
        ('/admin/djcelery/workerstate/add/', 'Django site admin'),
        ('/admin/doc/', 'Django site admin'),
        ('/admin/doc/bookmarklets/', 'Django site admin'),
        ('/admin/doc/filters/', 'Django site admin'),
        ('/admin/doc/models/', 'Django site admin'),
        ('/admin/doc/tags/', 'Django site admin'),
        ('/admin/doc/views/', 'Django site admin'),
        ('/admin/events/event/', 'Django site admin'),
        ('/admin/events/event/add/', 'Django site admin'),
        ('/admin/events/eventtimelabel/', 'Django site admin'),
        ('/admin/events/eventtimelabel/add/', 'Django site admin'),
        ('/admin/events/eventtype/', 'Django site admin'),
        ('/admin/events/eventtype/add/', 'Django site admin'),
        ('/admin/external_services/articleimportsource/', 'Django site admin'),
        ('/admin/external_services/articleimportsource/add/', 'Django site admin'),
        ('/admin/external_services/objectmapper/', 'Django site admin'),
        ('/admin/external_services/objectmapper/add/', 'Django site admin'),
        ('/admin/external_services/service/', 'Django site admin'),
        ('/admin/external_services/service/add/', 'Django site admin'),
        ('/admin/external_services/serviceactionlog/', 'Django site admin'),
        ('/admin/external_services/serviceactionlog/add/', 'Django site admin'),
        ('/admin/facebook_app/facebookappsettings/', 'Django site admin'),
        ('/admin/facebook_app/facebookappsettings/add/', 'Django site admin'),
        ('/admin/faqs/faqcategory/', 'Django site admin'),
        ('/admin/faqs/faqcategory/add/', 'Django site admin'),
        ('/admin/faqs/faqcontainer/', 'Django site admin'),
        ('/admin/faqs/faqcontainer/add/', 'Django site admin'),
        ('/admin/favorites/favorite/', 'Django site admin'),
        ('/admin/favorites/favorite/add/', 'Django site admin'),
        ('/admin/filebrowser/adjust-version/', 'Django site admin'),
        ('/admin/filebrowser/browse/', 'Django site admin'),
        ('/admin/filebrowser/delete-version/', 'Django site admin'),
        ('/admin/filebrowser/delete/', 'Django site admin'),
        ('/admin/filebrowser/delete_confirm/', 'Django site admin'),
        ('/admin/filebrowser/detail/', 'Django site admin'),
        ('/admin/filebrowser/get-version/', 'Django site admin'), # FIXME empty title
        ('/admin/filebrowser/upload_file/', 'Django site admin'), # FIXME AttributeError
        ('/admin/filebrowser/version/', 'Django site admin'),
        ('/admin/filebrowser/versions/', 'Django site admin'),
        ('/admin/flatpages/flatpage/', 'Django site admin'),
        ('/admin/flatpages/flatpage/add/', 'Django site admin'),
        ('/admin/groups_networks/grouptype/', 'Django site admin'),
        ('/admin/groups_networks/grouptype/add/', 'Django site admin'),
        ('/admin/groups_networks/persongroup/', 'Django site admin'),
        ('/admin/groups_networks/persongroup/add/', 'Django site admin'),
        ('/admin/i18n/area/', 'Django site admin'),
        ('/admin/i18n/area/add/', 'Django site admin'),
        ('/admin/i18n/country/', 'Django site admin'),
        ('/admin/i18n/country/add/', 'Django site admin'),
        ('/admin/i18n/countrylanguage/', 'Django site admin'),
        ('/admin/i18n/countrylanguage/add/', 'Django site admin'),
        ('/admin/i18n/language/', 'Django site admin'),
        ('/admin/i18n/language/add/', 'Django site admin'),
        ('/admin/i18n/nationality/', 'Django site admin'),
        ('/admin/i18n/nationality/add/', 'Django site admin'),
        ('/admin/i18n/phone/', 'Django site admin'),
        ('/admin/i18n/phone/add/', 'Django site admin'),
        ('/admin/i18n/timezone/', 'Django site admin'),
        ('/admin/i18n/timezone/add/', 'Django site admin'),
        ('/admin/image_mods/imagecropping/', 'Django site admin'),
        ('/admin/image_mods/imagecropping/add/', 'Django site admin'),
        ('/admin/image_mods/imagemodification/', 'Django site admin'),
        ('/admin/image_mods/imagemodification/add/', 'Django site admin'),
        ('/admin/image_mods/imagemodificationgroup/', 'Django site admin'),
        ('/admin/image_mods/imagemodificationgroup/add/', 'Django site admin'),
        ('/admin/individual_relations/individualrelation/', 'Django site admin'),
        ('/admin/individual_relations/individualrelation/add/', 'Django site admin'),
        ('/admin/individual_relations/individualrelationtype/', 'Django site admin'),
        ('/admin/individual_relations/individualrelationtype/add/', 'Django site admin'),
        ('/admin/institutions/institution/', 'Django site admin'),
        ('/admin/institutions/institution/add/', 'Django site admin'),
        ('/admin/institutions/institution/send-email/', 'Django site admin'),
        ('/admin/institutions/institutiontype/', 'Django site admin'),
        ('/admin/institutions/institutiontype/add/', 'Django site admin'),
        ('/admin/institutions/legalform/', 'Django site admin'),
        ('/admin/institutions/legalform/add/', 'Django site admin'),
        ('/admin/jsi18n/', 'Django site admin'),
        ('/admin/location/address/', 'Django site admin'),
        ('/admin/location/address/add/', 'Django site admin'),
        ('/admin/logout/', 'Django site admin'),
        ('/admin/mailchimp/campaign/', 'Django site admin'),
        ('/admin/mailchimp/campaign/add/', 'Django site admin'),
        ('/admin/mailchimp/mlist/', 'Django site admin'),
        ('/admin/mailchimp/mlist/add/', 'Django site admin'),
        ('/admin/mailchimp/settings/', 'Django site admin'),
        ('/admin/mailchimp/settings/add/', 'Django site admin'),
        ('/admin/mailchimp/subscription/', 'Django site admin'),
        ('/admin/mailchimp/subscription/add/', 'Django site admin'),
        ('/admin/mailing/emailmessage/', 'Django site admin'),
        ('/admin/mailing/emailmessage/add/', 'Django site admin'),
        ('/admin/mailing/emailtemplate/', 'Django site admin'),
        ('/admin/mailing/emailtemplate/add/', 'Django site admin'),
        ('/admin/mailing/emailtemplateplaceholder/', 'Django site admin'),
        ('/admin/mailing/emailtemplateplaceholder/add/', 'Django site admin'),
        ('/admin/marketplace/joboffer/', 'Django site admin'),
        ('/admin/marketplace/joboffer/add/', 'Django site admin'),
        ('/admin/marketplace/jobqualification/', 'Django site admin'),
        ('/admin/marketplace/jobqualification/add/', 'Django site admin'),
        ('/admin/marketplace/jobsector/', 'Django site admin'),
        ('/admin/marketplace/jobsector/add/', 'Django site admin'),
        ('/admin/marketplace/jobtype/', 'Django site admin'),
        ('/admin/marketplace/jobtype/add/', 'Django site admin'),
        ('/admin/media_gallery/mediagallery/', 'Django site admin'),
        ('/admin/media_gallery/mediagallery/add/', 'Django site admin'),
        ('/admin/media_gallery/portfoliosettings/', 'Django site admin'),
        ('/admin/media_gallery/portfoliosettings/add/', 'Django site admin'),
        ('/admin/media_gallery/section/', 'Django site admin'),
        ('/admin/media_gallery/section/add/', 'Django site admin'),
        ('/admin/memos/memocollection/', 'Django site admin'),
        ('/admin/memos/memocollection/add/', 'Django site admin'),
        ('/admin/messaging/internalmessage/', 'Django site admin'),
        ('/admin/messaging/internalmessage/add/', 'Django site admin'),
        ('/admin/navigation/navigationlink/', 'Django site admin'),
        ('/admin/navigation/navigationlink/add/', 'Django site admin'),
        ('/admin/notification/digest/', 'Django site admin'),
        ('/admin/notification/digest/add/', 'Django site admin'),
        ('/admin/notification/notice/', 'Django site admin'),
        ('/admin/notification/notice/add/', 'Django site admin'),
        ('/admin/notification/noticeemailtemplate/', 'Django site admin'),
        ('/admin/notification/noticeemailtemplate/add/', 'Django site admin'),
        ('/admin/notification/noticesetting/', 'Django site admin'),
        ('/admin/notification/noticesetting/add/', 'Django site admin'),
        ('/admin/notification/noticetype/', 'Django site admin'),
        ('/admin/notification/noticetype/add/', 'Django site admin'),
        ('/admin/notification/noticetypecategory/', 'Django site admin'),
        ('/admin/notification/noticetypecategory/add/', 'Django site admin'),
        ('/admin/optionset/emailtype/', 'Django site admin'),
        ('/admin/optionset/emailtype/add/', 'Django site admin'),
        ('/admin/optionset/imtype/', 'Django site admin'),
        ('/admin/optionset/imtype/add/', 'Django site admin'),
        ('/admin/optionset/individuallocationtype/', 'Django site admin'),
        ('/admin/optionset/individuallocationtype/add/', 'Django site admin'),
        ('/admin/optionset/institutionallocationtype/', 'Django site admin'),
        ('/admin/optionset/institutionallocationtype/add/', 'Django site admin'),
        ('/admin/optionset/phonetype/', 'Django site admin'),
        ('/admin/optionset/phonetype/add/', 'Django site admin'),
        ('/admin/optionset/prefix/', 'Django site admin'),
        ('/admin/optionset/prefix/add/', 'Django site admin'),
        ('/admin/optionset/salutation/', 'Django site admin'),
        ('/admin/optionset/salutation/add/', 'Django site admin'),
        ('/admin/optionset/urltype/', 'Django site admin'),
        ('/admin/optionset/urltype/add/', 'Django site admin'),
        ('/admin/password_change/', 'Django site admin'),
        ('/admin/password_change/done/', 'Django site admin'),
        ('/admin/people/individualtype/', 'Django site admin'),
        ('/admin/people/individualtype/add/', 'Django site admin'),
        ('/admin/people/person/', 'Django site admin'),
        ('/admin/people/person/add/', 'Django site admin'),
        ('/admin/people/person/send-email/', 'Django site admin'),
        ('/admin/permissions/perobjectgroup/', 'Django site admin'),
        ('/admin/permissions/perobjectgroup/add/', 'Django site admin'),
        ('/admin/permissions/rowlevelpermission/', 'Django site admin'),
        ('/admin/permissions/rowlevelpermission/add/', 'Django site admin'),
        ('/admin/profanity_filter/swearingcase/', 'Django site admin'),
        ('/admin/profanity_filter/swearingcase/add/', 'Django site admin'),
        ('/admin/profanity_filter/swearword/', 'Django site admin'),
        ('/admin/profanity_filter/swearword/add/', 'Django site admin'),
        ('/admin/redirects/redirect/', 'Django site admin'),
        ('/admin/redirects/redirect/add/', 'Django site admin'),
        ('/admin/resources/document/', 'Django site admin'),
        ('/admin/resources/document/add/', 'Django site admin'),
        ('/admin/resources/documenttype/', 'Django site admin'),
        ('/admin/resources/documenttype/add/', 'Django site admin'),
        ('/admin/resources/medium/', 'Django site admin'),
        ('/admin/resources/medium/add/', 'Django site admin'),
        ('/admin/site_specific/claimrequest/', 'Django site admin'),
        ('/admin/site_specific/claimrequest/add/', 'Django site admin'),
        ('/admin/site_specific/contextitem/', 'Django site admin'),
        ('/admin/site_specific/contextitem/add/', 'Django site admin'),
        ('/admin/site_specific/visit/', 'Django site admin'),
        ('/admin/site_specific/visit/add/', 'Django site admin'),
        ('/admin/sites/site/', 'Django site admin'),
        ('/admin/sites/site/add/', 'Django site admin'),
        ('/admin/slideshows/slideshow/', 'Django site admin'),
        ('/admin/slideshows/slideshow/add/', 'Django site admin'),
        ('/admin/structure/contextcategory/', 'Django site admin'),
        ('/admin/structure/contextcategory/add/', 'Django site admin'),
        ('/admin/structure/term/', 'Django site admin'),
        ('/admin/structure/term/add/', 'Django site admin'),
        ('/admin/structure/vocabulary/', 'Django site admin'),
        ('/admin/structure/vocabulary/add/', 'Django site admin'),
        ('/admin/tagging/tag/', 'Django site admin'),
        ('/admin/tagging/tag/add/', 'Django site admin'),
        ('/admin/tagging/taggeditem/', 'Django site admin'),
        ('/admin/tagging/taggeditem/add/', 'Django site admin'),
        ('/admin/templates/', 'Django site admin'), # FIXME current title is 'Creative City Berlin - login'
        ('/admin/tracker/concern/', 'Django site admin'),
        ('/admin/tracker/concern/add/', 'Django site admin'),
        ('/admin/tracker/ticket/', 'Django site admin'),
        ('/admin/tracker/ticket/add/', 'Django site admin'),
        ('/de/', 'Creative City Berlin'),
        ('/de/account/', 'Creative City Berlin'),
        ('/de/compatibility/', 'Creative City Berlin'),
        ('/de/contact/', 'Creative City Berlin'),
        ('/de/contact/alldone/', 'Creative City Berlin'),
        ('/de/documents/', 'Creative City Berlin'),
        ('/de/gmap/', 'Creative City Berlin'), # FIXME current title is 'Multipurpose Google Maps View'
        ('/de/groups/', 'Creative City Berlin'),
        # ('/de/helper/blank_doc/', 'Creative City Berlin'),
        # ('/de/helper/bookmark/', 'Creative City Berlin'),
        # ('/de/helper/country_lookup/', 'Creative City Berlin'),
        # ('/de/helper/site-visitors/', 'Creative City Berlin'),
        ('/de/institutions/', 'Creative City Berlin'),
        ('/de/invite/done/', 'Creative City Berlin'),
        ('/de/jobs/create-berlin-jobboard/', 'Creative City Berlin'), # FIXME current title is 'Job Board'
        ('/de/jobs/talent-in-berlin/', 'Creative City Berlin'), # FIXME empty title
        ('/de/jsi18n/', 'Creative City Berlin'), # FIXME empty title
        ('/de/jssettings/', 'Creative City Berlin'), # FIXME empty title
        ('/de/kreativarbeiten/best-practice/', 'Creative City Berlin'),
        ('/de/kreativarbeiten/blog/', 'Creative City Berlin'),
        ('/de/kreativarbeiten/blog/all/', 'Creative City Berlin'),
        ('/de/kreativarbeiten/blog/drafts/', 'Creative City Berlin'),
        ('/de/kreativarbeiten/contact/', 'Creative City Berlin'),
        ('/de/kreativarbeiten/contact/done/', 'Creative City Berlin'),
        ('/de/kreativarbeiten/newsfeed/', 'Creative City Berlin'), # FIXME empty title
        ('/de/kreativarbeiten/tweets/', 'Creative City Berlin'), # FIXME empty title
        ('/de/lists/', 'Creative City Berlin'),
        ('/de/livestream/', 'Creative City Berlin'),
        ('/de/login', 'Creative City Berlin'),
        ('/de/map/', 'Creative City Berlin'),
        ('/de/map/object-list/', 'Creative City Berlin'),
        ('/de/my-messages/json/', 'Creative City Berlin'), # FIXME empty title
        ('/de/my-profile/bookmarks/', 'Creative City Berlin'),
        ('/de/my-profile/delete/done/', 'Creative City Berlin'),
        ('/de/my-profile/favorites/', 'Creative City Berlin'),
        ('/de/my-profile/memos/', 'Creative City Berlin'),
        ('/de/news/', 'Creative City Berlin'),
        ('/de/news/articles/', 'Creative City Berlin'),
        ('/de/news/interviews/', 'Creative City Berlin'),
        ('/de/notification/feed/', 'Creative City Berlin'), # FIXME empty title
        ('/de/password_change/done/', 'Creative City Berlin'),
        ('/de/password_reset/', 'Creative City Berlin'),
        ('/de/password_reset/complete/', 'Creative City Berlin'),
        ('/de/password_reset/done/', 'Creative City Berlin'),
        ('/de/people/', 'Creative City Berlin'),
        # ('/de/recrop/', 'Creative City Berlin'),
        ('/de/register/', 'Creative City Berlin'),
        ('/de/register/done/', 'Creative City Berlin'),
        ('/de/search/', 'Creative City Berlin'),
        ('/de/search/full/', 'Creative City Berlin'),
        ('/de/simplesearch/', 'Creative City Berlin'),
        # ('/de/sitemap.xml', 'Creative City Berlin'),
        ('/de/styleguide/', 'Creative City Berlin'),
        ('/de/styleguide/colors/', 'Creative City Berlin'),
        ('/de/styleguide/forms/', 'Creative City Berlin'),
        ('/de/styleguide/grid/', 'Creative City Berlin'),
        ('/de/styleguide/images/', 'Creative City Berlin'),
        ('/de/styleguide/typography/', 'Creative City Berlin'),
        ('/de/subscribe4info/', 'Creative City Berlin'),
        ('/de/subscribe4info/done/', 'Creative City Berlin'),
        # ('/de/tagging_autocomplete/list', 'Creative City Berlin'),
        ('/de/ticket/', 'Creative City Berlin'),
        ('/de/tweets/', 'Creative City Berlin'), # FIXME empty title
        ('/helper/bookmark/', 'Creative City Berlin'), # FIXME empty title
        ('/helper/country_lookup/', 'Creative City Berlin'), # FIXME empty title
        ('/helper/site-visitors/', 'Creative City Berlin'), # FIXME empty title
        # ('/recrop/', 'Creative City Berlin'),
        ('/tagging_autocomplete/list', 'Creative City Berlin'), # FIXME empty title
    )

    suite = unittest.TestSuite()
    suite.addTests(TitleTest(url_path, title) for url_path, title in known_values)
    return suite


if __name__ == '__main__':
    unittest.TextTestRunner().run(suite())
