# -*- coding: utf-8 -*-
CMS_PERMISSION = True
CMS_URL_OVERWRITE = False
CMS_USE_TINYMCE = True
CMS_REDIRECTS = True
CMS_MEDIA_ROOT = os.path.join(JETSON_MEDIA_ROOT, 'cms/')
CMS_MEDIA_URL = JETSON_MEDIA_URL + 'cms/'
CMS_SEO_FIELDS = True
CMS_MEDIA_PATH = "cms/"
CMS_LANGUAGES = LANGUAGES

CMS_DBGETTEXT = False
CMS_DBGETTEXT_SLUGS = []

CMS_SOFTROOT = True
CMS_SHOW_START_DATE = True
CMS_SHOW_END_DATE = True
CMS_MENU_TITLE_OVERWRITE = True
CMS_TEMPLATE_INHERITANCE_MAGIC = True


TINYMCE_JS_URL = STATIC_URL + 'admin/tinymce/jscripts/tiny_mce/tiny_mce.js'
PLACEHOLDER_FRONTEND_EDITING = True

CMS_PAGE_CHOICES_CACHE_KEY = "CMS_PAGE_CHOICES"
CMS_PUBLIC_FOR = 'all'
CMS_PLUGIN_CONTEXT_PROCESSORS = ()
CMS_PLUGIN_PROCESSORS = ()
