POST /events/doc/_search HTTP/1.1
Host: localhost:9200
Connection: keep-alive
Content-Type: application/json
Cache-Control: no-cache

{
  "sort": [
    "start",
    "title_de"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "is_published": true
          }
        },
        {
          "range": {
            "start": {
              "gte": "2018-09-24T12:09:54.879928"
            }
          }
        }
      ]
    }
  },
  "from": 0,
  "size": 24
}