# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models
from base_libs.utils.misc import south_clean_multilingual_fields
from base_libs.utils.misc import south_cleaned_fields

class Migration(SchemaMigration):
    
    def forwards(self, orm):
        
        # Adding model 'LegalForm'
        db.create_table('institutions_legalform', south_cleaned_fields((
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('creation_date', self.gf('django.db.models.fields.DateTimeField')()),
            ('modified_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('slug', self.gf('django.db.models.fields.SlugField')(unique=True, max_length=255, db_index=True)),
            ('title', self.gf('base_libs.models.fields.MultilingualCharField')(max_length=200, null=True)),
            ('sort_order', self.gf('django.db.models.fields.IntegerField')(default=0)),
            ('title_de', self.gf('django.db.models.fields.CharField')(u'title', null=False, primary_key=False, db_column=None, default='', editable=True, max_length=200, db_tablespace='', blank=False, unique=False, db_index=False)),
            ('title_en', self.gf('django.db.models.fields.CharField')(u'title', null=False, primary_key=False, db_column=None, default='', editable=True, max_length=200, db_tablespace='', blank=False, unique=False, db_index=False)),
        )))
        db.send_create_signal('institutions', ['LegalForm'])

        # Adding model 'InstitutionType'
        db.create_table('institutions_institutiontype', south_cleaned_fields((
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('slug', self.gf('django.db.models.fields.SlugField')(unique=True, max_length=255, db_index=True)),
            ('sort_order', self.gf('django.db.models.fields.IntegerField')(default=0, blank=True)),
            ('parent', self.gf('mptt.fields.TreeForeignKey')(blank=True, related_name='child_set', null=True, to=orm['institutions.InstitutionType'])),
            ('title', self.gf('base_libs.models.fields.MultilingualCharField')(max_length=255, null=True)),
            ('title_de', self.gf('django.db.models.fields.CharField')(u'title', null=False, primary_key=False, db_column=None, default='', editable=True, max_length=255, db_tablespace='', blank=False, unique=False, db_index=False)),
            ('title_en', self.gf('django.db.models.fields.CharField')(u'title', null=False, primary_key=False, db_column=None, default='', editable=True, max_length=255, db_tablespace='', blank=False, unique=False, db_index=False)),
            ('lft', self.gf('django.db.models.fields.PositiveIntegerField')(db_index=True)),
            ('rght', self.gf('django.db.models.fields.PositiveIntegerField')(db_index=True)),
            ('tree_id', self.gf('django.db.models.fields.PositiveIntegerField')(db_index=True)),
            ('level', self.gf('django.db.models.fields.PositiveIntegerField')(db_index=True)),
        )))
        db.send_create_signal('institutions', ['InstitutionType'])

        # Adding model 'Institution'
        db.create_table('institutions_institution', south_cleaned_fields((
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('creation_date', self.gf('django.db.models.fields.DateTimeField')()),
            ('modified_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('is_appointment_based', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('mon_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('mon_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('mon_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('mon_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('tue_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('tue_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('tue_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('tue_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('wed_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('wed_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('wed_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('wed_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('thu_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('thu_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('thu_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('thu_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('fri_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('fri_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('fri_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('fri_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sat_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sat_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sat_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sat_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sun_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sun_break_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sun_break_open', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('sun_close', self.gf('django.db.models.fields.TimeField')(null=True, blank=True)),
            ('exceptions', self.gf('base_libs.models.fields.MultilingualTextField')(default='', null=True, blank=True)),
            ('title', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('title2', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('slug', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('parent', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['institutions.Institution'], null=True, blank=True)),
            ('description', self.gf('base_libs.models.fields.MultilingualTextField')(default='', null=True, blank=True)),
            ('image', self.gf('filebrowser.fields.FileBrowseField')(directory='institutions/', max_length=255, extensions=['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff'], blank=True)),
            ('status', self.gf('django.db.models.fields.CharField')(default='draft', max_length=20, blank=True)),
            ('legal_form', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='legal_form_institution', null=True, to=orm['institutions.LegalForm'])),
            ('access', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_parking_avail', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_wlan_avail', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_non_profit', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('tax_id_number', self.gf('django.db.models.fields.CharField')(max_length=100, blank=True)),
            ('vat_id_number', self.gf('django.db.models.fields.CharField')(max_length=100, blank=True)),
            ('is_card_visa_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_card_mastercard_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_card_americanexpress_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_paypal_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_cash_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_transaction_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_prepayment_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_on_delivery_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_invoice_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_ec_maestro_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_giropay_ok', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('establishment_yyyy', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('establishment_mm', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('nof_employees', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('exceptions_de', self.gf('base_libs.models.fields.ExtendedTextField')(u'Exceptions for working hours', unique_for_month=None, unique_for_date=None, primary_key=False, db_column=None, max_length=None, unique_for_year=None, rel=None, blank=True, unique=False, db_tablespace='', db_index=False)),
            ('exceptions_de_markup_type', self.gf('django.db.models.fields.CharField')('Markup type', default='pt', max_length=10, blank=False)),
            ('exceptions_en', self.gf('base_libs.models.fields.ExtendedTextField')(u'Exceptions for working hours', unique_for_month=None, unique_for_date=None, primary_key=False, db_column=None, max_length=None, unique_for_year=None, rel=None, blank=True, unique=False, db_tablespace='', db_index=False)),
            ('exceptions_en_markup_type', self.gf('django.db.models.fields.CharField')('Markup type', default='pt', max_length=10, blank=False)),
            ('exceptions_markup_type', self.gf('django.db.models.fields.CharField')('Markup type', default='pt', max_length=10, blank=False)),
            ('description_de', self.gf('base_libs.models.fields.ExtendedTextField')(u'Description', unique_for_month=None, unique_for_date=None, primary_key=False, db_column=None, max_length=None, unique_for_year=None, rel=None, blank=True, unique=False, db_tablespace='', db_index=False)),
            ('description_de_markup_type', self.gf('django.db.models.fields.CharField')('Markup type', default='pt', max_length=10, blank=False)),
            ('description_en', self.gf('base_libs.models.fields.ExtendedTextField')(u'Description', unique_for_month=None, unique_for_date=None, primary_key=False, db_column=None, max_length=None, unique_for_year=None, rel=None, blank=True, unique=False, db_tablespace='', db_index=False)),
            ('description_en_markup_type', self.gf('django.db.models.fields.CharField')('Markup type', default='pt', max_length=10, blank=False)),
            ('description_markup_type', self.gf('django.db.models.fields.CharField')('Markup type', default='pt', max_length=10, blank=False)),
        )))
        db.send_create_signal('institutions', ['Institution'])

        # Adding M2M table for field institution_types on 'Institution'
        db.create_table('institutions_institution_institution_types', (
            ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True)),
            ('institution', models.ForeignKey(orm['institutions.institution'], null=False)),
            ('institutiontype', models.ForeignKey(orm['institutions.institutiontype'], null=False))
        ))
        db.create_unique('institutions_institution_institution_types', ['institution_id', 'institutiontype_id'])

        # Adding M2M table for field context_categories on 'Institution'
        db.create_table('institutions_institution_context_categories', (
            ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True)),
            ('institution', models.ForeignKey(orm['institutions.institution'], null=False)),
            ('contextcategory', models.ForeignKey(orm['structure.contextcategory'], null=False))
        ))
        db.create_unique('institutions_institution_context_categories', ['institution_id', 'contextcategory_id'])

        # Adding model 'InstitutionalContact'
        db.create_table('institutions_institutionalcontact', south_cleaned_fields((
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('institution', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['institutions.Institution'])),
            ('location_type', self.gf('django.db.models.fields.related.ForeignKey')(default=None, to=orm['optionset.InstitutionalLocationType'])),
            ('location_title', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_primary', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('is_temporary', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('validity_start_yyyy', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('validity_start_mm', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('validity_start_dd', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('validity_end_yyyy', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('validity_end_mm', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('validity_end_dd', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('postal_address', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_address', null=True, to=orm['location.Address'])),
            ('is_billing_address', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('is_shipping_address', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('phone0_type', self.gf('django.db.models.fields.related.ForeignKey')(default=None, related_name='institutional_contacts0', null=True, blank=True, to=orm['optionset.PhoneType'])),
            ('phone0_country', self.gf('django.db.models.fields.CharField')(default='49', max_length=4, blank=True)),
            ('phone0_area', self.gf('django.db.models.fields.CharField')(default='30', max_length=6, blank=True)),
            ('phone0_number', self.gf('django.db.models.fields.CharField')(max_length=25, blank=True)),
            ('is_phone0_default', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('is_phone0_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('phone1_type', self.gf('django.db.models.fields.related.ForeignKey')(default=None, related_name='institutional_contacts1', null=True, blank=True, to=orm['optionset.PhoneType'])),
            ('phone1_country', self.gf('django.db.models.fields.CharField')(default='49', max_length=4, blank=True)),
            ('phone1_area', self.gf('django.db.models.fields.CharField')(default='30', max_length=6, blank=True)),
            ('phone1_number', self.gf('django.db.models.fields.CharField')(max_length=25, blank=True)),
            ('is_phone1_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_phone1_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('phone2_type', self.gf('django.db.models.fields.related.ForeignKey')(default=None, related_name='institutional_contacts2', null=True, blank=True, to=orm['optionset.PhoneType'])),
            ('phone2_country', self.gf('django.db.models.fields.CharField')(default='49', max_length=4, blank=True)),
            ('phone2_area', self.gf('django.db.models.fields.CharField')(max_length=6, blank=True)),
            ('phone2_number', self.gf('django.db.models.fields.CharField')(max_length=25, blank=True)),
            ('is_phone2_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_phone2_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('url0_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts0', null=True, to=orm['optionset.URLType'])),
            ('url0_link', self.gf('base_libs.models.fields.URLField')(max_length=200, blank=True)),
            ('is_url0_default', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('is_url0_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('url1_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts1', null=True, to=orm['optionset.URLType'])),
            ('url1_link', self.gf('base_libs.models.fields.URLField')(max_length=200, blank=True)),
            ('is_url1_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_url1_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('url2_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts2', null=True, to=orm['optionset.URLType'])),
            ('url2_link', self.gf('base_libs.models.fields.URLField')(max_length=200, blank=True)),
            ('is_url2_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_url2_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('im0_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts0', null=True, to=orm['optionset.IMType'])),
            ('im0_address', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_im0_default', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('is_im0_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('im1_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts1', null=True, to=orm['optionset.IMType'])),
            ('im1_address', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_im1_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_im1_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('im2_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts2', null=True, to=orm['optionset.IMType'])),
            ('im2_address', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_im2_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_im2_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('email0_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts0', null=True, to=orm['optionset.EmailType'])),
            ('email0_address', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_email0_default', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('is_email0_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('email1_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts1', null=True, to=orm['optionset.EmailType'])),
            ('email1_address', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_email1_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_email1_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('email2_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='institutional_contacts2', null=True, to=orm['optionset.EmailType'])),
            ('email2_address', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('is_email2_default', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_email2_on_hold', self.gf('django.db.models.fields.BooleanField')(default=False)),
        )))
        db.send_create_signal('institutions', ['InstitutionalContact'])
    
    
    def backwards(self, orm):
        
        # Deleting model 'LegalForm'
        db.delete_table('institutions_legalform')

        # Deleting model 'InstitutionType'
        db.delete_table('institutions_institutiontype')

        # Deleting model 'Institution'
        db.delete_table('institutions_institution')

        # Removing M2M table for field institution_types on 'Institution'
        db.delete_table('institutions_institution_institution_types')

        # Removing M2M table for field context_categories on 'Institution'
        db.delete_table('institutions_institution_context_categories')

        # Deleting model 'InstitutionalContact'
        db.delete_table('institutions_institutionalcontact')
    
    
    models = {
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('app_label', 'name')", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'i18n.country': {
            'Meta': {'object_name': 'Country'},
            'adm_area': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'}),
            'display': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'iso2_code': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '2', 'primary_key': 'True'}),
            'iso3_code': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '56'}),
            'name_de': ('django.db.models.fields.CharField', [], {'max_length': '56', 'blank': 'True'}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'sort_order': ('django.db.models.fields.PositiveIntegerField', [], {'default': '20'}),
            'territory_of': ('django.db.models.fields.CharField', [], {'max_length': '3', 'blank': 'True'})
        },
        'institutions.institution': {
            'Meta': {'ordering': "('title', 'title2')", 'object_name': 'Institution'},
            'access': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'context_categories': ('mptt.fields.TreeManyToManyField', [], {'to': "orm['structure.ContextCategory']", 'symmetrical': 'False', 'blank': 'True'}),
            'creation_date': ('django.db.models.fields.DateTimeField', [], {}),
            'description': ('base_libs.models.fields.MultilingualTextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'description_de': ('base_libs.models.fields.ExtendedTextField', ["u'Description'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'description_de_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'description_en': ('base_libs.models.fields.ExtendedTextField', ["u'Description'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'description_en_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'description_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'establishment_mm': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'establishment_yyyy': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'exceptions': ('base_libs.models.fields.MultilingualTextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'exceptions_de': ('base_libs.models.fields.ExtendedTextField', ["u'Exceptions for working hours'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'exceptions_de_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'exceptions_en': ('base_libs.models.fields.ExtendedTextField', ["u'Exceptions for working hours'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'exceptions_en_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'exceptions_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'fri_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'fri_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'fri_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'fri_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'image': ('filebrowser.fields.FileBrowseField', [], {'directory': "'institutions/'", 'max_length': '255', 'extensions': "['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff']", 'blank': 'True'}),
            'institution_types': ('mptt.fields.TreeManyToManyField', [], {'to': "orm['institutions.InstitutionType']", 'symmetrical': 'False'}),
            'is_appointment_based': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_card_americanexpress_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_card_mastercard_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_card_visa_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_cash_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_ec_maestro_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_giropay_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_invoice_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_non_profit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_on_delivery_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_parking_avail': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_paypal_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_prepayment_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_transaction_ok': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_wlan_avail': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'legal_form': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'legal_form_institution'", 'null': 'True', 'to': "orm['institutions.LegalForm']"}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'mon_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'mon_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'mon_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'mon_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'nof_employees': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['institutions.Institution']", 'null': 'True', 'blank': 'True'}),
            'sat_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'sat_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'sat_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'sat_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'status': ('django.db.models.fields.CharField', [], {'default': "'draft'", 'max_length': '20', 'blank': 'True'}),
            'sun_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'sun_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'sun_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'sun_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'tax_id_number': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'thu_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'thu_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'thu_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'thu_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'title2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'tue_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'tue_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'tue_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'tue_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'vat_id_number': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'wed_break_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'wed_break_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'wed_close': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'}),
            'wed_open': ('django.db.models.fields.TimeField', [], {'null': 'True', 'blank': 'True'})
        },
        'institutions.institutionalcontact': {
            'Meta': {'ordering': "['-is_primary']", 'object_name': 'InstitutionalContact'},
            'email0_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'email0_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts0'", 'null': 'True', 'to': "orm['optionset.EmailType']"}),
            'email1_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'email1_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts1'", 'null': 'True', 'to': "orm['optionset.EmailType']"}),
            'email2_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'email2_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts2'", 'null': 'True', 'to': "orm['optionset.EmailType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'im0_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'im0_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts0'", 'null': 'True', 'to': "orm['optionset.IMType']"}),
            'im1_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'im1_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts1'", 'null': 'True', 'to': "orm['optionset.IMType']"}),
            'im2_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'im2_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts2'", 'null': 'True', 'to': "orm['optionset.IMType']"}),
            'institution': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['institutions.Institution']"}),
            'is_billing_address': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_email0_default': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_email0_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_email1_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_email1_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_email2_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_email2_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_im0_default': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_im0_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_im1_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_im1_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_im2_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_im2_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_phone0_default': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_phone0_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_phone1_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_phone1_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_phone2_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_phone2_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_primary': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_shipping_address': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_temporary': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_url0_default': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_url0_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_url1_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_url1_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_url2_default': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_url2_on_hold': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'location_title': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'location_type': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'to': "orm['optionset.InstitutionalLocationType']"}),
            'phone0_area': ('django.db.models.fields.CharField', [], {'default': "'30'", 'max_length': '6', 'blank': 'True'}),
            'phone0_country': ('django.db.models.fields.CharField', [], {'default': "'49'", 'max_length': '4', 'blank': 'True'}),
            'phone0_number': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'phone0_type': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'related_name': "'institutional_contacts0'", 'null': 'True', 'blank': 'True', 'to': "orm['optionset.PhoneType']"}),
            'phone1_area': ('django.db.models.fields.CharField', [], {'default': "'30'", 'max_length': '6', 'blank': 'True'}),
            'phone1_country': ('django.db.models.fields.CharField', [], {'default': "'49'", 'max_length': '4', 'blank': 'True'}),
            'phone1_number': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'phone1_type': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'related_name': "'institutional_contacts1'", 'null': 'True', 'blank': 'True', 'to': "orm['optionset.PhoneType']"}),
            'phone2_area': ('django.db.models.fields.CharField', [], {'max_length': '6', 'blank': 'True'}),
            'phone2_country': ('django.db.models.fields.CharField', [], {'default': "'49'", 'max_length': '4', 'blank': 'True'}),
            'phone2_number': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'phone2_type': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'related_name': "'institutional_contacts2'", 'null': 'True', 'blank': 'True', 'to': "orm['optionset.PhoneType']"}),
            'postal_address': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_address'", 'null': 'True', 'to': "orm['location.Address']"}),
            'url0_link': ('base_libs.models.fields.URLField', [], {'max_length': '200', 'blank': 'True'}),
            'url0_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts0'", 'null': 'True', 'to': "orm['optionset.URLType']"}),
            'url1_link': ('base_libs.models.fields.URLField', [], {'max_length': '200', 'blank': 'True'}),
            'url1_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts1'", 'null': 'True', 'to': "orm['optionset.URLType']"}),
            'url2_link': ('base_libs.models.fields.URLField', [], {'max_length': '200', 'blank': 'True'}),
            'url2_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'institutional_contacts2'", 'null': 'True', 'to': "orm['optionset.URLType']"}),
            'validity_end_dd': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'validity_end_mm': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'validity_end_yyyy': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'validity_start_dd': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'validity_start_mm': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'validity_start_yyyy': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'institutions.institutiontype': {
            'Meta': {'ordering': "['tree_id', 'lft']", 'object_name': 'InstitutionType'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'level': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'lft': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'parent': ('mptt.fields.TreeForeignKey', [], {'blank': 'True', 'related_name': "'child_set'", 'null': 'True', 'to': "orm['institutions.InstitutionType']"}),
            'rght': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'tree_id': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'})
        },
        'institutions.legalform': {
            'Meta': {'ordering': "['sort_order']", 'object_name': 'LegalForm'},
            'creation_date': ('django.db.models.fields.DateTimeField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '200', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '200', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '200', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'})
        },
        'location.address': {
            'Meta': {'object_name': 'Address'},
            'city': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'country': ('django.db.models.fields.related.ForeignKey', [], {'default': "'DE'", 'to': "orm['i18n.Country']", 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'postal_code': ('django.db.models.fields.CharField', [], {'max_length': '10', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'street_address': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'street_address2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'street_address3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'})
        },
        'optionset.emailtype': {
            'Meta': {'ordering': "['sort_order', 'title']", 'object_name': 'EmailType'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'})
        },
        'optionset.imtype': {
            'Meta': {'ordering': "['sort_order', 'title']", 'object_name': 'IMType'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'})
        },
        'optionset.institutionallocationtype': {
            'Meta': {'ordering': "['sort_order', 'title']", 'object_name': 'InstitutionalLocationType'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'})
        },
        'optionset.phonetype': {
            'Meta': {'ordering': "['sort_order', 'title']", 'object_name': 'PhoneType'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'vcard_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'})
        },
        'optionset.urltype': {
            'Meta': {'ordering': "['sort_order', 'title']", 'object_name': 'URLType'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'})
        },
        'permissions.rowlevelpermission': {
            'Meta': {'object_name': 'RowLevelPermission', 'db_table': "'auth_rowlevelpermission'"},
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'negative': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'object_id': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255'}),
            'owner_content_type': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'owner'", 'to': "orm['contenttypes.ContentType']"}),
            'owner_object_id': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255'}),
            'permission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['auth.Permission']"})
        },
        'structure.contextcategory': {
            'Meta': {'ordering': "['tree_id', 'lft']", 'object_name': 'ContextCategory'},
            'body': ('base_libs.models.fields.MultilingualTextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'body_de': ('base_libs.models.fields.ExtendedTextField', ["u'body'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'body_de_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'body_en': ('base_libs.models.fields.ExtendedTextField', ["u'body'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'body_en_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'body_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'creative_sectors': ('mptt.fields.TreeManyToManyField', [], {'symmetrical': 'False', 'to': "orm['structure.Term']", 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'image': ('filebrowser.fields.FileBrowseField', [], {'max_length': '255', 'extensions': "['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff']", 'blank': 'True'}),
            'is_applied4document': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_applied4event': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_applied4institution': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_applied4person': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_applied4persongroup': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'level': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'lft': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'parent': ('mptt.fields.TreeForeignKey', [], {'blank': 'True', 'related_name': "'child_set'", 'null': 'True', 'to': "orm['structure.ContextCategory']"}),
            'rght': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'sysname': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'tree_id': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'})
        },
        'structure.term': {
            'Meta': {'ordering': "['tree_id', 'lft']", 'object_name': 'Term'},
            'body': ('base_libs.models.fields.MultilingualTextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'body_de': ('base_libs.models.fields.ExtendedTextField', ["u'body'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'body_de_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'body_en': ('base_libs.models.fields.ExtendedTextField', ["u'body'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'body_en_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'body_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'image': ('filebrowser.fields.FileBrowseField', [], {'max_length': '255', 'extensions': "['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff']", 'blank': 'True'}),
            'level': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'lft': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'parent': ('mptt.fields.TreeForeignKey', [], {'blank': 'True', 'related_name': "'child_set'", 'null': 'True', 'to': "orm['structure.Term']"}),
            'rght': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sort_order': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'sysname': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'tree_id': ('django.db.models.fields.PositiveIntegerField', [], {'db_index': 'True'}),
            'vocabulary': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['structure.Vocabulary']"})
        },
        'structure.vocabulary': {
            'Meta': {'object_name': 'Vocabulary'},
            'body': ('base_libs.models.fields.MultilingualTextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'body_de': ('base_libs.models.fields.ExtendedTextField', ["u'body'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'body_de_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'body_en': ('base_libs.models.fields.ExtendedTextField', ["u'body'"], {'unique_for_month': 'None', 'unique_for_date': 'None', 'primary_key': 'False', 'db_column': 'None', 'max_length': 'None', 'unique_for_year': 'None', 'rel': 'None', 'blank': 'True', 'unique': 'False', 'db_tablespace': "''", 'db_index': 'False'}),
            'body_en_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'body_markup_type': ('django.db.models.fields.CharField', ["'Markup type'"], {'default': "'pt'", 'max_length': '10', 'blank': 'False'}),
            'hierarchy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'image': ('filebrowser.fields.FileBrowseField', [], {'max_length': '255', 'extensions': "['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff']", 'blank': 'True'}),
            'slug': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'sysname': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '255', 'db_index': 'True'}),
            'title': ('base_libs.models.fields.MultilingualCharField', [], {'max_length': '255', 'null': 'True'}),
            'title_de': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'}),
            'title_en': ('django.db.models.fields.CharField', ["u'title'"], {'null': 'False', 'primary_key': 'False', 'db_column': 'None', 'default': "''", 'editable': 'True', 'max_length': '255', 'db_tablespace': "''", 'blank': 'False', 'unique': 'False', 'db_index': 'False'})
        }
    }
    south_clean_multilingual_fields(models)
    
    complete_apps = ['institutions']
