# -*- coding: UTF-8 -*-
from django.conf import settings

from jetson.apps.groups_networks.models import URL_ID_PERSONGROUP, URL_ID_PERSONGROUPS, DEFAULT_LOGO_4_PERSONGROUP, DEFAULT_FORM_LOGO_4_PERSONGROUP, DEFAULT_SMALL_LOGO_4_PERSONGROUP

def groups_networks(request=None):
    d = {
        'URL_ID_PERSONGROUP': URL_ID_PERSONGROUP,
        'URL_ID_PERSONGROUPS': URL_ID_PERSONGROUPS,
        'DEFAULT_LOGO_4_PERSONGROUP': DEFAULT_LOGO_4_PERSONGROUP,
        'DEFAULT_FORM_LOGO_4_PERSONGROUP': DEFAULT_FORM_LOGO_4_PERSONGROUP,
        'DEFAULT_SMALL_LOGO_4_PERSONGROUP': DEFAULT_SMALL_LOGO_4_PERSONGROUP,
        }
    return d

